language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - mv .env.example .env
  - travis_retry composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit